config/routes.rb
Rails.application.routes.draw do
  get 'top' => 'homes#top'
  get 'home/about' => 'homes#about'
  # ログイン後表示ページを設定
  root 'homes#top'
  devise_for :users
  resources :books
  resources :users, only: [:index, :edit, :update, :show]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/book.rb
class Book < ApplicationRecord
  # 投稿が空ならエラー
  validates :title, presence: true
  validates :body, presence: true

  # 入力は200文字以下
  validates :body, length: { maximum: 200}

  belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  validates :name, presence: true
  # nameは2文字以上20文字以下
  validates :name, length: { minimum: 2}
  validates :name, length: { maximum: 20}
  # introductionは50文字以下
  validates :introduction, length: { maximum: 50}

  attachment :profile_image

  has_many :books, dependent: :destroy
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
before_action :configure_permitted_parameters, if: :devise_controller?

# ログイン後のページ指定
def after_sign_in_path_for(resource)
  user_path(resource)
end
# ログアウト後のページ指定
def after_sign_out_path_for(resource)
  top_path
end

  protected
  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:email])
  end
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
before_action :authenticate_user!
before_action :correct_user, only: [:edit, :update]

  def new
    @book = Book.new
  end

  def create
    @book = Book.new(book_params)
    @book.user_id = current_user.id
    @user = User.find(current_user.id)
    if @book.save
      redirect_to books_path
      flash[:success] = 'Book was successfully created.'
    else
      @books = Book.all
      render :index
    end
  end

  def show
    @book = Book.find(params[:id])
    @user = User.find(current_user.id)
    @userf = User.find_by(id: @book.user_id)
  end

  def index
  	@books = Book.all
  	@book = Book.new
    @user = User.find(current_user.id)
  end

  def edit
  	@book = Book.find(params[:id])
  	flash[:success] = 'Book was successfully created.'
  end

  def update
  	@book = Book.find(params[:id])
  	if @book.update(book_params)
  	  redirect_to book_path(book_params)
    else
      render :edit
    end
  end

  def destroy
  	book = Book.find(params[:id])
  	book.destroy
  	redirect_to books_path
  end

  def book_params
  	# params.require(:オブジェクト名).permit(:カラム名)
  	params.require(:book).permit(:title, :body, :user_id)
  end

  def correct_user
  @book = current_user.books.find_by(id: params[:id])
    unless @book
      redirect_to books_path
    end
  end
end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  def top
  end

  def about
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
before_action :authenticate_user!
  def index
  	@user = User.find(current_user.id)
  	@users = User.all
  	@book = Book.new
  end

  def edit
  	@user = User.find(params[:id])
    flash[:success] = 'You have updated user successfully.'
    if @user.id != current_user.id
      redirect_to user_path(current_user.id)
    end
  end

  def update
    @user = User.find(params[:id])
    flash[:success] = 'You have updated user successfully.'
  	if @user.update(user_params)
  	redirect_to user_path(current_user.id)
    else
      render :edit
    end
  end

  def show
  	@user = User.find(params[:id])
  	@book = Book.new
  	# ログイン中のユーザーの投稿のみ表示する為
  	# schema.rbのcreate_table "books", force: :cascade do |t|からとってきている
  	# ユーザー　の　データを全て持ってくる
  	@loginuserdate = @user.books
  end

private
  def user_params
    # permitデータの操作を許可、これ(カラム名)書かないと変更しても更新されない
    # 管理者画面とかを作成する時はここにカラム書いたらダメ、今の段階では全カラム記述
    params.require(:user).permit(:name, :introduction, :profile_image)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/books/_list.html.erb
<h1>User info</h1>

<% if book.errors.any? %>
  <h2><%= pluralize(book.errors.count, "error")%> prohibited this product from being saved:</h2>
  <% book.errors.full_messages.each do |message| %>
    <%= message %>
  <% end %>
<% end %>

<table>
  <tr>
    <th></th><td><%= attachment_image_tag current_user, :profile_image, :fill, 100, 100, fallback:"no_image.jpg", size:"50×50" %></td>
  </tr>
  <tr>
    <th>name</th><td><%= current_user.name %></td>
  </tr>
  <tr>
    <th>introduction</th><td><%= current_user.introduction %></td>
  </tr>
</table>

<%= link_to edit_user_path(user) do %>
  <button type="button" class="btn col-xs-12 btn btn-default glyphicon glyphicon-wrench">
  </button>
<% end %>

<h2>New book</h2>
<%= form_for(@book) do |f| %>
  <h4>title</h4>
  <%= f.text_field :title %>
  <h4>Opinion</h4>
  <%= f.text_area :body %><br />
  <%= f.submit 'Create Book' %>
<% end %>

app/views/books/edit.html.erb
<h1>Editing Book</h1>

<% if @book.errors.any? %>
  <h2><%= pluralize(@book.errors.count, "error")%> prohibited this product from being saved:</h2>
  <% @book.errors.full_messages.each do |message| %>
    <%= message %>
  <% end %>
<% end %>

<%= form_for(@book) do |f| %>
  <h4>title</h4>
  <%= f.text_field :title %>
  <h4>body</h4>
  <%= f.text_area :body %>
  <%= f.submit 'Update Book' %>
<% end %>

<%= link_to "Show", book_path(@book.id) %>
<%= link_to "Back", books_path %>

app/views/books/index.html.erb
<!-- create、editアクションのflash[:success]を呼び出している -->
<%= flash[:success] %>

<div class="container">
  <div class="row">

    <div class="col-xs-3">
      <%= render 'books/list', user: @user, book: @book %>
    </div>

    <div class="col-xs-9">
      <h1>Books</h1>
      <table>
        <tr>
          <th></th>
          <th>Title</th>
          <th>Opinion</th>
        </tr>
        <% @books.each do |book| %>
          <tr>
            <td><%= link_to (attachment_image_tag book.user, :profile_image, :fill, 100, 100, fallback:"no_image.jpg", size:"50×50"), user_path(book.user_id) %></td>
            <td><%= link_to book.title, book_path(book.id) %></td>
            <td><%= book.body %></td>
          </tr>
        <% end %>
      </table>
    </div>
  </div>
</div>

app/views/books/new.html.erb
<h1>新規投稿</h1>

<% if @book.errors.any? %>
  <h2><%= pluralize(@book.errors.count, "error")%> prohibited this product from being saved:</h2>
  <% @book.errors.full_messages.each do |message| %>
    <%= message %>
  <% end %>
<% end %>

<%= form_for(@book) do |f| %>
  <h4>title</h4>
  <%= f.text_field :title %>
  <h4>body</h4>
  <%= f.text_area :body %>
  <%= f.submit '投稿' %>
<% end %>

app/views/books/show.html.erb
<div class="container">
  <div class="row">

    <div class="col-xs-3">
      <%= render 'books/list', user: @user, book: @book %>
    </div>

    <div class="col-xs-9">
      <h2>Book detail</h2>
      <%= link_to (attachment_image_tag @userf, :profile_image, :fill, 100, 100, fallback:"no_image.jpg", size:"50×50"), user_path(@book.user_id) %>
      <%= link_to @userf.name, user_path(@book.user_id) %>
      <h4>title</h4>
      <%= @book.title %>
      <h4>body</h4>
      <%= @book.body %>

      <% if user_signed_in? && current_user.id == @book.user_id %>
        <%= link_to "Edit", edit_book_path(@book.id) %>
        <%= link_to "Destroy", book_path(@book.id), method: :delete, "data-confirm" => "本当に消しますか？" %>
      <% end %>
    </div>
  </div>
</div>

app/views/homes/about.html.erb
<h1>Welcome to Bookers!</h1>
<p>CopyRight Infratop.inc</p>

app/views/homes/top.html.erb
<div class="homes_top">
  <div class="container">
    <div class="row">
      <div class="col-xs-3">
      </div>
      <div class="col-xs-6">
        <div class="homes_top_head">
		  <h2>welcome to <span class="glyphicon glyphicon-book" aria-hidden="true"></span>Bookers !!</h2>
		  <p>In <span class="glyphicon glyphicon-book" aria-hidden="true"></span>Bookers,</p>
	      <p>you can share and exchange your opinions , inpressions , and emotions</p>
	      <p>about various books!</p>
        </div>
      </div>
      <div class="col-xs-3">
      </div>
    </div>

    <div class="row">
      <div class="col-xs-3">
      </div>
      <div class="col-xs-6">
        <div class="homes_top_foot">
          <div class="homes_top_Login"><%= link_to "Log in", new_user_session_path, class: "btn btn-info col-xs-10 col-xs-offset-1" %>
          </div>
          <div class="homes_top_SignUp"><%= link_to "Sign Up", new_user_registration_path, class: "btn btn-success col-xs-10 col-xs-offset-1" %>
          </div>
        </div>
      </div>
      <div class="col-xs-3">
      </div>
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Pra</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <header>
      <nav class="nav-left">
        <ul>
          <li>Bookers</li>
        </ul>
      </nav>

      <nav class="nav-right">
        <% if user_signed_in? %>
          <ul>
            <li><span class="glyphicon glyphicon-home" aria-hidden="true"></span><%= link_to "Home", user_path(current_user.id) %></li>
            <li><span class="glyphicon glyphicon-user" aria-hidden="true"></span><%= link_to "Users", users_path %></li>
            <li><span class="glyphicon glyphicon-book" aria-hidden="true"></span><%= link_to "Books", books_path %></li>
            <li><span class="glyphicon glyphicon-log-in" aria-hidden="true"></span><%= link_to "logout", destroy_user_session_path, method: :delete %></li>
          </ul>
        <% else %>
          <ul>
            <li><span class="glyphicon glyphicon-home" aria-hidden="true"></span><%= link_to "Home", root_path %></li>
            <li><span class="glyphicon glyphicon-link" aria-hidden="true"></span><%= link_to "About", home_about_path %></li>
            <li><span class="glyphicon glyphicon-edit" aria-hidden="true"></span><%= link_to "sign up", new_user_registration_path %></li>
            <li><span class="glyphicon glyphicon-log-in" aria-hidden="true"></span><%= link_to "login", new_user_session_path %></li>
          </ul>
        <% end %>
      </nav>
    </header>

    <% flash.each do |key, value| %>
      <%= content_tag(:div, value, class: "#{key}") %>
    <% end %>

    <%= yield %>

    <footer>
      <div class="container">
        <div class="row">
          <div class="col-xs-9">
          </div>
          <div class="col-xs-3">
            <p>CopyRight Infratop.inc</p>
          </div>
        </div>
      </div>
    </footer>
  </body>
</html>

app/views/users/edit.html.erb
<h2>User info</h2>

<% if @user.errors.any? %>
  <h2><%= pluralize(@user.errors.count, "error")%> prohibited this product from being saved:</h2>
  <% @user.errors.full_messages.each do |message| %>
    <%= message %>
  <% end %>
<% end %>

<%= form_for(@user) do |f| %>
  <%= f.label :name %><br />
  <%= f.text_field :name, autofocus: true, autocomplete: "name" %><br />


  <%= f.label :image %>
  <!-- 画像選択フォームの表示 -->
  <!-- profile_image部分はカラム名だが_idはつけない -->
  <%= f.attachment_field :profile_image %>

  <%= f.label :introduction %><br />
  <%= f.text_area :introduction, autofocus: true, autocomplete: "introduction" %><br />

  <%= f.submit 'Update User' %>
<% end %>

app/views/users/index.html.erb
<div class="container">
  <div class="row">

    <div class="col-xs-3">
      <%= render 'books/list', user: @user, book: @book %>
    </div>

    <div class="col-xs-9">
      <h1>Users</h1>
      <table>
        <tr>
          <th>image</th>
          <th>name</th>
          <th></th>
          <th></th>
        </tr>

        <% @users.each do |user| %>
          <tr>
            <td><%= attachment_image_tag user, :profile_image, :fill, 100, 100, fallback:"no_image.jpg", size:"50×50" %></td>
            <td><%= user.name %></td>
            <td><%= user.introduction %></td>
            <td><%= link_to "Show", user_path(user.id) %></td>
          </tr>
        <% end %>
      </table>
    </div>
  </div>
</div>

app/views/users/show.html.erb
<div class="container">
  <div class="row">

    <div class="col-xs-3">
      <%= render 'books/list', user: @user, book: @book %>
    </div>

    <div class="col-xs-9">
      <h1>Books</h1>

      <table>
        <tr>
          <th></th>
          <th></th>
          <th>Opinion</th>
        </tr>

        <% @loginuserdate.each do |book| %>
          <tr>
            <td><%= attachment_image_tag book.user, :profile_image, :fill, 100, 100, fallback:"no_image.jpg", size:"50×50" %></td>
            <td><%= link_to book.title, book_path(book.id) %></td>
            <td><%= book.body %></td>
          </tr>
        <% end %>
      </table>
    </div>
  </div>
</div>